engines:
  eslint:
    enabled: true
exclude_paths:
- "app/assets/javascripts/redactor.js"
- "app/assets/javascripts/openseadragon.js"
- "app/assets/javascripts/components.js"
- "app/assets/javascripts/dropzone.js"
