engines:
  tslint:
    enabled: true
    channel: beta
    
ratings:
   paths:
   - "app/"

exclude_paths:
- "bin/"
- "config/"
- "db/"
- "lib/"
- "log/"
- "public/"
- "solr/"
- "spec/"

# test commit
