development:
  token: srDhuT6CjWS2as8eyMtR
  url: http://localhost:3005
test:
  token: srDhuT6CjWS2as8eyMtR
  url: http://localhost:3005
pre_production:
  token: 4N7mjqZLgospCNgc7YXS
  url: https://apipprd.library.nd.edu
production:
  token: QmwbTAXxp8RW7VqrB18V
  url: https://api.library.nd.edu
